import express from 'express';
import cors from 'cors';
import multer from 'multer';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const app = express();
const upload = multer({ dest: 'uploads/' });

app.use(cors());
app.use(express.json());

// Parse tnsnames.ora content
function parseTnsnames(content) {
  const entries = [];
  const lines = content.split('\n');
  let currentEntry = null;
  let currentKey = null;
  let braceLevel = 0;
  let inEntry = false;
  let currentAlias = '';

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();
    
    // Skip empty lines and comments
    if (!line || line.startsWith('#')) continue;

    // Check for alias (ends with =)
    if (line.endsWith('=') && !inEntry) {
      if (currentEntry) {
        entries.push(currentEntry);
      }
      currentAlias = line.replace('=', '').trim();
      currentEntry = {
        alias: currentAlias,
        host: '',
        port: '1521',
        serviceName: '',
        protocol: 'TCP',
        description: currentAlias
      };
      inEntry = true;
      continue;
    }

    // Parse key-value pairs inside entry
    if (inEntry && line.includes('=')) {
      const equalsIndex = line.indexOf('=');
      const key = line.substring(0, equalsIndex).trim().toUpperCase();
      let value = line.substring(equalsIndex + 1).trim();

      // Handle parentheses continuation
      if (value === '(') {
        braceLevel = 1;
        let j = i + 1;
        value = '';
        while (j < lines.length && braceLevel > 0) {
          const contLine = lines[j].trim();
          if (contLine === '(') braceLevel++;
          if (contLine === ')') braceLevel--;
          if (braceLevel > 0 && contLine !== '(') {
            value += contLine + ' ';
          }
          j++;
        }
        i = j - 1;
      }

      // Extract values
      if (key === 'HOST') {
        currentEntry.host = value;
      } else if (key === 'PORT') {
        currentEntry.port = value;
      } else if (key === 'SERVICE_NAME') {
        currentEntry.serviceName = value;
      } else if (key === 'SID') {
        currentEntry.serviceName = value;
      } else if (key === 'PROTOCOL') {
        currentEntry.protocol = value;
      } else if (key === 'DESCRIPTION') {
        currentEntry.description = value || currentAlias;
      }
    }

    // End of entry
    if (inEntry && (line === ')' || line === ') ')) {
      if (currentEntry) {
        entries.push(currentEntry);
      }
      currentEntry = null;
      inEntry = false;
    }
  }

  if (currentEntry) {
    entries.push(currentEntry);
  }

  return entries;
}

// Generate tnsnames.ora content from entries
function generateTnsnames(entries) {
  let content = '# tnsnames.ora Network Configuration\n';
  content += `# Generated by TNS Names Manager\n`;
  content += `# ${new Date().toISOString()}\n\n`;

  entries.forEach((entry, index) => {
    if (index > 0) {
      content += '\n';
    }
    content += `${entry.alias} =\n`;
    content += `  (DESCRIPTION =\n`;
    content += `    (ADDRESS = (PROTOCOL = ${entry.protocol || 'TCP'})(HOST = ${entry.host})(PORT = ${entry.port || '1521'}))\n`;
    content += `    (CONNECT_DATA =\n`;
    content += `      (SERVICE_NAME = ${entry.serviceName})\n`;
    content += `    )\n`;
    content += `  )\n`;
  });

  return content;
}

// Validate tnsnames entry
function validateEntry(entry) {
  const errors = [];
  
  if (!entry.alias || entry.alias.trim() === '') {
    errors.push('Alias is required');
  }
  
  if (!entry.host || entry.host.trim() === '') {
    errors.push('Host is required');
  }
  
  if (!entry.port || entry.port.trim() === '') {
    errors.push('Port is required');
  } else if (isNaN(parseInt(entry.port)) || parseInt(entry.port) < 1 || parseInt(entry.port) > 65535) {
    errors.push('Port must be a valid port number (1-65535)');
  }
  
  if (!entry.serviceName || entry.serviceName.trim() === '') {
    errors.push('Service name is required');
  }
  
  return errors;
}

// API Routes

// Parse uploaded file
app.post('/api/parse', upload.single('file'), (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: 'No file uploaded' });
    }

    const content = fs.readFileSync(req.file.path, 'utf-8');
    const entries = parseTnsnames(content);
    
    // Clean up uploaded file
    fs.unlinkSync(req.file.path);

    res.json({ entries });
  } catch (error) {
    res.status(500).json({ error: 'Failed to parse file: ' + error.message });
  }
});

// Parse raw content
app.post('/api/parse-content', (req, res) => {
  try {
    const { content } = req.body;
    if (!content) {
      return res.status(400).json({ error: 'No content provided' });
    }

    const entries = parseTnsnames(content);
    res.json({ entries });
  } catch (error) {
    res.status(500).json({ error: 'Failed to parse content: ' + error.message });
  }
});

// Validate entries
app.post('/api/validate', (req, res) => {
  try {
    const { entries } = req.body;
    if (!entries || !Array.isArray(entries)) {
      return res.status(400).json({ error: 'Invalid entries' });
    }

    const validationResults = entries.map(entry => ({
      alias: entry.alias,
      errors: validateEntry(entry)
    }));

    const hasErrors = validationResults.some(r => r.errors.length > 0);
    
    res.json({ valid: !hasErrors, results: validationResults });
  } catch (error) {
    res.status(500).json({ error: 'Validation failed: ' + error.message });
  }
});

// Generate tnsnames.ora content
app.post('/api/generate', (req, res) => {
  try {
    const { entries } = req.body;
    if (!entries || !Array.isArray(entries)) {
      return res.status(400).json({ error: 'Invalid entries' });
    }

    // Validate all entries first
    const allErrors = [];
    entries.forEach((entry, index) => {
      const errors = validateEntry(entry);
      if (errors.length > 0) {
        allErrors.push({ index, alias: entry.alias, errors });
      }
    });

    if (allErrors.length > 0) {
      return res.status(400).json({ error: 'Validation failed', details: allErrors });
    }

    const content = generateTnsnames(entries);
    res.json({ content });
  } catch (error) {
    res.status(500).json({ error: 'Failed to generate content: ' + error.message });
  }
});

// Export as JSON
app.post('/api/export-json', (req, res) => {
  try {
    const { entries } = req.body;
    if (!entries || !Array.isArray(entries)) {
      return res.status(400).json({ error: 'Invalid entries' });
    }

    res.json({ json: JSON.stringify(entries, null, 2) });
  } catch (error) {
    res.status(500).json({ error: 'Failed to export JSON: ' + error.message });
  }
});

// Export as YAML
app.post('/api/export-yaml', (req, res) => {
  try {
    const { entries } = req.body;
    if (!entries || !Array.isArray(entries)) {
      return res.status(400).json({ error: 'Invalid entries' });
    }

    const yaml = entries.map(entry => 
      `${entry.alias}:\n  host: ${entry.host}\n  port: ${entry.port}\n  service_name: ${entry.serviceName}\n  protocol: ${entry.protocol || 'TCP'}`
    ).join('\n\n');

    res.json({ yaml });
  } catch (error) {
    res.status(500).json({ error: 'Failed to export YAML: ' + error.message });
  }
});

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log(`TNS Names Manager server running on port ${PORT}`);
});